{
 "title": "Confluent Open Source",
 "tags": [ "4.1.0" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Confluent Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cp_kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec)",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec)",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_network_requestmetrics_requestspersec_produce)",
     "legendFormat": "Produce"
    },
    {
     "expr": "sum(cp_kafka_network_requestmetrics_requestspersec_fetchconsumer)",
     "legendFormat": "Consumer Fetch"
    },
    {
     "expr": "sum(cp_kafka_network_requestmetrics_requestspersec_fetchfollower)",
     "legendFormat": "Follower Fetch"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec)",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec)",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec)",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec)",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_kafkarequesthandlerpool_requesthandleravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Confluent Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(cp_zookeeper_quorumsize)" }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_numaliveconnections)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_zookeeper_outstandingrequests",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount)"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "singlestat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount)"
    }
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_minrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_avgrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cp_zookeeper_maxrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  { "title": "Confluent Schema Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Number of Kafka Schema Registry servers",
   "type": "singlestat",
   "description": "Number of Kafka Schema Registry servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_schema_registry_jetty_metrics_connections_active)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_active"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "singlestat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_opened_rate"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "singlestat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_closed_rate"
    }
   ]
  },
  { "title": "Confluent Kafka REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Number of Kafka REST servers",
   "type": "singlestat",
   "description": "Number of Kafka REST servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_rest_jetty_metrics_connections_active)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_rest_jetty_metrics_connections_active"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "singlestat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_rest_jetty_metrics_connections_opened_rate"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "singlestat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 52 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_rest_jetty_metrics_connections_closed_rate"
    }
   ]
  }
 ]
}