{{ if .Values.securityContextConstraints.create }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    kubernetes.io/description: "full copy of nonroot SecurityContextConstraints.
    nonroot provides all features of the restricted SCC but allows users to run with any non-root UID.
    The user must specify the UID or it must be specified on the by the manifest of the container runtime."
    release.openshift.io/create-only: "true"
{{ if .Values.securityContextConstraints.name }}
  name: {{ .Values.securityContextConstraints.name }}
{{ else }}
  name: {{ .Namespace.Name }}-{{ .Release.Name }}-cp-ksql-server
{{ end }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
{{ if .Values.serviceAccount.name }}
  - system:serviceaccount:{{ .Release.Name }}:{{ .Values.serviceAccount.name }}
{{ else }}
{{ if .Values.serviceAccount.create }}
  - system:serviceaccount:{{ .Release.Name }}:{{ .Release.Name }}-cp-ksql-server
{{ end }}
{{ end }}
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
{{ end }}
