apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-control-center.fullname" . }}
  labels:
    app: {{ template "cp-control-center.name" . }}
    chart: {{ template "cp-control-center.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: cc-http
      port: {{ .Values.service.port }}
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "cp-control-center.name" . }}
    release: {{ .Release.Name }}
