{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka.fullname" . }}
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
  {{- end }}