apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.awsCredentialsSecret.secretId }}
      versionId: {{ .Values.awsCredentialsSecret.versionId }}
