{{- $fullName := include ".Values.name.fullname" . -}}
{{- $ingressPath := .Values.envs.kakfa-rest.paths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.envs.kakfa-rest.certificate_arn }}
    alb.ingress.kubernetes.io/group.name: eks-lb-{{ .Values.appLabels.region }}
    alb.ingress.kubernetes.io/group.order: '10'
    alb.ingress.kubernetes.io/healthcheck-path: /_ping
    kubernetes.io/ingress.class: alb
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    region: {{ .Values.appLabels.region }}
  name: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.envs.kakfa-rest.ingress_host }}
    http:
      paths:
      {{- range $ingressPath }}
        - path: {{ . }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: 80
          pathType: ImplementationSpecific
      {{- end }}
