{{- if and .Values.prometheus.jmx.enabled .Values.prometheus.jmx.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}
  namespace: {{ .Values.prometheus.jmx.serviceMonitor.namespace }}
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  jobLabel: {{ template "cp-kafka-rest.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "cp-kafka-rest.name" . }}
      release: {{ .Release.Name }}
      component: metrics
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.prometheus.jmx.serviceMonitor.interval }}
  targetLabels:
    - release
{{- end }}
