{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "cp-kafka-rest.name" . }}
      chart: {{ template "cp-kafka-rest.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end }}
