= Using Minikube for Local Kubernetes

== Install Minikube and Drivers

Minikube v0.23.0 or higher is required for docker server https://github.com/moby/moby/pull/31352[17.05], which adds support for using `ARG` in `FROM` in your `Dockerfile`.

1. [Minikube installation instructions](https://github.com/kubernetes/minikube).

2. [Minikube drivers](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md). Minikube uses Docker Machine to manage the Kubernetes VM so it benefits from the driver plugin architecture that Docker Machine uses to provide a consistent way to manage various VM providers. Minikube embeds VirtualBox and VMware Fusion drivers so there are no additional steps to use them. However, other drivers require an extra binary to be present in the host PATH.

== Start Minikube

1. Start Minikube, note that the memory has been increased to 6096 MB.

[source,shell]
----
$ minikube start --kubernetes-version v1.8.0 --cpus 4 --memory 6096 --vm-driver=xhyve --v=8
----

2. Check status until both minikube and cluster are in Running state

[source,shell]
----
$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.106
----

3. Configure the minikube VM.

[source,shell]
----
$ minikube ssh
  sudo ip link set docker0 promisc on
  exit
----

4. Set the context.

[source,shell]
----
$ eval $(minikube docker-env)

$ kubectl config set-context minikube.internal --cluster=minikube --user=minikube
Context "minikube.internal" modified.

$ kubectl config use-context minikube.internal
Switched to context "minikube.internal".
----

== Verify Local Kubernetes Environment

[source,shell]
----
$ kubectl config current-context
minikube.internal

$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.106:8443
KubeDNS is running at https://192.168.99.106:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----

== Stop Minikube

[source,shell]
----
$ minikube delete
----
