apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-headless
  labels:
  {{ include "cp-zookeeper.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.serverPort }}
      name: server
    - port: {{ .Values.leaderElectionPort }}
      name: leader-election
  clusterIP: None
  selector:
    app: {{ template "cp-zookeeper.name" . }}
    release: {{ .Release.Name }}
