apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-pdb
  labels:
  {{ include "cp-zookeeper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "cp-zookeeper.name" . }}
      release: {{ .Release.Name }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
