{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{ if .Values.serviceAccount.name }}
  name: {{ .Values.serviceAccount.name }}
{{ else }}
  name: {{ .Release.Name }}-zookeeper
{{ end }}
  namespace: {{ .Release.Namespace }}
{{ end }}
